# Site settings
title: FineTaboo's Notes
description: >
    FineTaboo's Notes
author: FineTaboo
email: your@e.mail
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/FineTaboo/FineTaboo.github.io" # the base hostname & protocol for your site
twitter_username: YourTwitter
github_username:  YourGitHub

disqus_shortname: https-finetaboo-github-io

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed

gems:
  - jemoji
  - jekyll-sitemap
# - amp-jekyll # Acceletrated Mobile Pages

# AMP Settings
# ampdir: amp/
# enable_amp: true

# Google Analytics
# google_analytics: UA-XXXXXXXX-X
